docs: update docs structure

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -1,10 +1,10 @@
-#!/bin/bash -e
+#!/bin/bash
 
 # regex to validate in commit msg
-commit_regex='^(TML-[A-Z0-9]{2,4}|merge|hotfix|release)'
-error_msg="Aborting commit. Your commit message must start with JIRA code (eg: 'TML-1111') or 'merge|hotfix|release'"
+techmelyTicketReg='^(TML-[A-Z0-9]{2,4}|merge|hotfix|release)'
+errorMsg="Aborting commit. Your commit message must start with JIRA code (eg: 'TML-1111') or 'merge|hotfix|release'"
 
-if ! grep -iqE "$commit_regex" "$1"; then
-    echo "$error_msg" >&2
+if ! grep -iqE "$techmelyTicketReg" "$1"; then
+    echo "$errorMsg" >&2
     exit 1
 fi
